import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS as baseCOLORS } from '../constants';

// Module-level cache: StyleSheet.create() is expensive. We cache the result
// keyed by isDark (true/false) so it runs at most twice per app lifetime.
const _themeColorsCache = new Map();
const _stylesCache = new Map();

export const getThemeColors = (isDark) => {
  if (_themeColorsCache.has(isDark)) return _themeColorsCache.get(isDark);
  let result;
  if (isDark) {
    result = {
      primary: '#22c55e',
      primaryDark: '#16a34a',
      background: '#0f172a',
      card: '#1e293b',
      textDark: '#f8fafc',
      textMuted: '#94a3b8',
      border: '#334155',
      inputBg: '#1e293b',
      shadowColor: '#000',
      shadowOpacity: 0.3,
      backdrop: 'rgba(15, 23, 42, 0.75)',
      buttonText: '#ffffff',
      chipBackground: '#334155',
      statsGreenBg: '#064e3b',
      statsGreenText: '#4ade80',
      deleteBtnBg: '#451a03',
      deleteBtnText: '#f97316',
      accentGreenBg: '#052e16',
      accentGreenBorder: '#22c55e',
    };
  } else {
    result = {
      primary: baseCOLORS.primary,
      primaryDark: baseCOLORS.primaryDark,
      background: baseCOLORS.background,
      card: baseCOLORS.card,
      textDark: baseCOLORS.textDark,
      textMuted: baseCOLORS.textMuted,
      border: baseCOLORS.border,
      inputBg: '#ffffff',
      shadowColor: '#000',
      shadowOpacity: 0.06,
      backdrop: 'rgba(15, 23, 42, 0.45)',
      buttonText: '#ffffff',
      chipBackground: '#f1f5f9',
      statsGreenBg: '#dcfce7',
      statsGreenText: '#15803d',
      deleteBtnBg: '#fee2e2',
      deleteBtnText: '#b91c1c',
      accentGreenBg: '#f0fdf4',
      accentGreenBorder: '#86B749',
    };
  }
  _themeColorsCache.set(isDark, result);
  return result;
};

export const getStyles = (isDark) => {
  if (_stylesCache.has(isDark)) return _stylesCache.get(isDark);
  const C = getThemeColors(isDark);
  const sheet = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: C.background,
    },
    authContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
      backgroundColor: C.background,
    },
    logoFull: {
      width: 180,
      height: 180,
      marginBottom: 8,
      resizeMode: 'contain',
    },
    tagline: {
      fontSize: 18,
      color: '#86B749',
      marginBottom: 24,
      fontWeight: '700',
    },
    authCard: {
      width: '100%',
      backgroundColor: C.card,
      borderRadius: 16,
      padding: 20,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 8,
      elevation: 3,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ? StatusBar.currentHeight + 10 : 35) : 16,
      backgroundColor: C.card,
      borderBottomWidth: 1,
      borderBottomColor: C.border,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logoSmall: {
      width: 32,
      height: 32,
      marginRight: 8,
      resizeMode: 'contain',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: C.textDark,
    },
    headerSubtitle: {
      fontSize: 12,
      color: C.textMuted,
    },
    logoutText: {
      color: C.textMuted,
      fontSize: 13,
    },
    backButton: {
      fontSize: 14,
      color: C.primary,
    },
    saveText: {
      fontSize: 14,
      color: C.primaryDark,
      fontWeight: '600',
    },
    content: {
      flex: 1,
      padding: 16,
    },
    input: {
      backgroundColor: C.inputBg,
      padding: 12,
      borderRadius: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: C.border,
      fontSize: 15,
      color: C.textDark,
    },
    inputSmall: {
      backgroundColor: C.inputBg,
      padding: 10,
      borderRadius: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: C.border,
      fontSize: 14,
      color: C.textDark,
    },
    primaryButton: {
      backgroundColor: C.primary,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    primaryButtonText: {
      color: C.buttonText,
      fontSize: 15,
      fontWeight: '600',
    },
    secondaryButton: {
      backgroundColor: 'transparent',
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: C.primary,
      marginBottom: 10,
    },
    secondaryButtonText: {
      color: C.primary,
      fontSize: 15,
      fontWeight: '600',
    },
    outlinedSmallButton: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: C.border,
      alignItems: 'center',
      marginRight: 6,
      backgroundColor: C.inputBg,
    },
    outlinedSmallButtonText: {
      fontSize: 13,
      color: C.textDark,
    },
    primarySmallButton: {
      marginTop: 8,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: C.primary,
      alignItems: 'center',
    },
    primarySmallButtonText: {
      fontSize: 14,
      color: C.buttonText,
      fontWeight: '600',
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
      marginTop: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: C.textDark,
    },
    sectionLabel: {
      fontSize: 13,
      color: C.textMuted,
      marginBottom: 4,
    },
    activeCard: {
      backgroundColor: C.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 6,
      elevation: 2,
    },
    activeWorkoutName: {
      fontSize: 18,
      fontWeight: '700',
      color: C.textDark,
      marginBottom: 8,
    },
    chipPrimary: {
      alignSelf: 'flex-start',
      backgroundColor: C.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
    },
    chipPrimaryText: {
      color: C.buttonText,
      fontSize: 13,
      fontWeight: '600',
    },
    chipOutline: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: C.primary,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    chipOutlineText: {
      fontSize: 12,
      color: C.primary,
      fontWeight: '600',
    },
    workoutCard: {
      backgroundColor: C.card,
      padding: 16,
      borderRadius: 16,
      marginBottom: 14,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 4,
      elevation: 2,
    },
    workoutHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    deleteHeaderButton: {
      backgroundColor: C.deleteBtnBg,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
    },
    deleteHeaderButtonText: {
      color: C.deleteBtnText,
      fontSize: 12,
      fontWeight: '600',
    },
    workoutName: {
      fontSize: 16,
      fontWeight: '700',
      color: C.textDark,
    },
    exerciseCount: {
      color: C.textMuted,
      fontSize: 13,
    },
    workoutActions: {
      flexDirection: 'row',
      marginTop: 10,
    },
    fab: {
      position: 'absolute',
      right: 20,
      bottom: 110,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: C.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
    },
    fabIcon: {
      color: C.buttonText,
      fontSize: 30,
      lineHeight: 30,
    },
    bottomNav: {
      flexDirection: 'row',
      backgroundColor: C.card,
      borderTopWidth: 1,
      borderTopColor: C.border,
      paddingBottom: 10,
      paddingTop: 8,
    },
    navButton: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 4,
    },
    navButtonActive: {
      borderTopWidth: 2,
      borderTopColor: C.textDark,
    },
    navLabel: {
      fontSize: 11,
      color: C.textMuted,
      fontWeight: '500',
    },
    navLabelActive: {
      color: C.textDark,
      fontWeight: '700',
    },
    activeExerciseCard: {
      backgroundColor: C.card,
      padding: 16,
      borderRadius: 16,
      marginBottom: 14,
    },
    exerciseHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    muscleManWrapper: {
      alignItems: 'center',
      backgroundColor: C.card,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: C.border,
    },
    muscleManLabel: {
      fontSize: 12,
      color: C.textMuted,
      marginBottom: 8,
    },
    musclePlaceholder: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: C.primary + '20',
      justifyContent: 'center',
      alignItems: 'center',
    },
    musclePlaceholderText: {
      fontSize: 34,
    },
    restTimeButton: {
      backgroundColor: C.primary,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 999,
      marginRight: 10,
    },
    restTimeButtonDisabled: {
      backgroundColor: C.border,
    },
    restTimeButtonText: {
      color: C.buttonText,
      fontSize: 13,
      fontWeight: '600',
    },
    exerciseTitleContainer: {
      flex: 1,
    },
    activeExerciseName: {
      fontSize: 16,
      fontWeight: '700',
      color: C.textDark,
    },
    muscleGroup: {
      color: C.textMuted,
      fontSize: 13,
    },
    setHeaderRow: {
      flexDirection: 'row',
      marginBottom: 4,
      paddingHorizontal: 4,
    },
    setHeaderText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      color: C.textMuted,
      textAlign: 'center',
    },
    setRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 4,
      backgroundColor: C.border + '30',
      borderRadius: 10,
      marginBottom: 6,
    },
    setCellSerie: {
      flex: 0.6,
      textAlign: 'center',
      fontWeight: '600',
      color: C.textDark,
    },
    setCellInput: {
      flex: 1,
      backgroundColor: C.inputBg,
      borderRadius: 8,
      paddingVertical: 4,
      paddingHorizontal: 6,
      borderWidth: 1,
      borderColor: C.border,
      marginHorizontal: 4,
      textAlign: 'center',
      fontSize: 13,
      color: C.textDark,
    },
    checkButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 2,
      borderColor: C.primary,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: C.inputBg,
    },
    checkButtonComplete: {
      backgroundColor: C.primary,
    },
    checkText: {
      fontSize: 16,
      color: C.buttonText,
      fontWeight: '700',
    },
    addSetRowButton: {
      marginTop: 6,
      alignSelf: 'flex-start',
      backgroundColor: C.primary + '20',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
    },
    addSetRowButtonText: {
      color: C.primaryDark,
      fontSize: 12,
      fontWeight: '600',
    },
    deleteSetSwipeButton: {
      backgroundColor: C.deleteBtnBg,
      justifyContent: 'center',
      alignItems: 'center',
      width: 90,
      borderRadius: 10,
      marginVertical: 2,
    },
    deleteSetSwipeText: {
      color: C.deleteBtnText,
      fontSize: 12,
      fontWeight: '600',
    },
    editSwipeButton: {
      backgroundColor: '#dbeafe',
      justifyContent: 'center',
      alignItems: 'center',
      width: 90,
      borderRadius: 10,
      marginVertical: 2,
    },
    editSwipeText: {
      color: '#1d4ed8',
      fontSize: 12,
      fontWeight: '600',
    },
    workoutTimerContainer: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: C.card,
      borderBottomWidth: 1,
      borderBottomColor: C.border,
    },
    workoutTimerLabel: {
      fontSize: 12,
      color: C.textMuted,
    },
    workoutTimerValue: {
      fontSize: 20,
      fontWeight: '700',
      color: C.textDark,
    },
    timerBar: {
      backgroundColor: C.primary,
      paddingVertical: 16,
      paddingHorizontal: 20,
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: C.primaryDark,
    },
    timerLabel: {
      color: 'rgba(255,255,255,0.75)',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    timerCountdown: {
      color: C.buttonText,
      fontSize: 42,
      fontWeight: '800',
      letterSpacing: 2,
      marginBottom: 12,
    },
    timerControlsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    timerControlButton: {
      backgroundColor: 'rgba(0,0,0,0.20)',
      paddingVertical: 9,
      paddingHorizontal: 22,
      borderRadius: 999,
    },
    timerControlText: {
      color: C.buttonText,
      fontSize: 15,
      fontWeight: '700',
    },
    timerControlButtonSecondary: {
      backgroundColor: C.inputBg,
      paddingVertical: 9,
      paddingHorizontal: 26,
      borderRadius: 999,
    },
    timerControlTextSecondary: {
      color: C.primary,
      fontSize: 15,
      fontWeight: '700',
    },
    workoutFooter: {
      flexDirection: 'row',
      padding: 16,
      backgroundColor: C.card,
      borderTopWidth: 1,
      borderTopColor: C.border,
    },
    footerButtonFlex: {
      flex: 1,
      marginHorizontal: 4,
    },
    historyCard: {
      backgroundColor: C.card,
      padding: 16,
      borderRadius: 16,
      marginBottom: 12,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 4,
      elevation: 2,
    },
    historyName: {
      fontSize: 16,
      fontWeight: '700',
      color: C.textDark,
    },
    historyDate: {
      color: C.textMuted,
      marginTop: 4,
      fontSize: 13,
    },
    historyExercises: {
      color: C.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    historyDuration: {
      color: C.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    emptyText: {
      textAlign: 'center',
      color: C.textMuted,
      marginTop: 40,
      fontSize: 15,
    },
    historyEditSetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    historyEditInput: {
      flex: 1,
      backgroundColor: C.inputBg,
      borderRadius: 8,
      paddingVertical: 4,
      paddingHorizontal: 6,
      borderWidth: 1,
      borderColor: C.border,
      marginHorizontal: 4,
      textAlign: 'center',
      fontSize: 12,
      color: C.textDark,
    },
    muscleGroupSection: {
      marginBottom: 20,
    },
    muscleGroupTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: C.textDark,
      marginBottom: 8,
    },
    exerciseListItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: C.card,
      padding: 12,
      borderRadius: 12,
      marginBottom: 6,
    },
    exerciseListName: {
      fontSize: 14,
      color: C.textDark,
    },
    customBadge: {
      backgroundColor: C.primary,
      color: C.buttonText,
      fontSize: 10,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
    },
    addExerciseButton: {
      backgroundColor: C.primary,
      padding: 14,
      marginHorizontal: 16,
      marginTop: 12,
      borderRadius: 14,
      alignItems: 'center',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: C.backdrop,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '85%',
      backgroundColor: C.card,
      borderRadius: 18,
      padding: 20,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 12,
      elevation: 6,
    },
    modalContentLarge: {
      width: '90%',
      maxHeight: '80%',
      backgroundColor: C.card,
      borderRadius: 18,
      padding: 20,
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 12,
      elevation: 6,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 16,
      color: C.textDark,
      textAlign: 'center',
    },
    modalButtons: {
      flexDirection: 'row',
      marginTop: 10,
    },
    modalButtonFlex: {
      flex: 1,
      marginHorizontal: 4,
    },
    exerciseList: {
      maxHeight: 260,
      marginBottom: 10,
    },
    selectableExercise: {
      padding: 12,
      backgroundColor: C.border + '25',
      borderRadius: 10,
      marginBottom: 6,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    selectedExercise: {
      borderColor: C.primary,
      backgroundColor: C.primary + '15',
    },
    exerciseForm: {
      marginTop: 10,
    },
    selectedExerciseText: {
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 10,
      color: C.textDark,
      textAlign: 'center',
    },
    viewExerciseItem: {
      backgroundColor: C.border + '25',
      padding: 12,
      borderRadius: 10,
      marginBottom: 8,
    },
    viewExerciseName: {
      fontSize: 14,
      fontWeight: '600',
      color: C.textDark,
      marginBottom: 4,
    },
    viewExerciseDetails: {
      fontSize: 12,
      color: C.textMuted,
    },
    muscleGroupSelectorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 8,
    },
    groupChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: C.chipBackground,
      marginRight: 6,
      marginBottom: 6,
    },
    groupChipSelected: {
      backgroundColor: C.primary,
    },
    groupChipText: {
      fontSize: 12,
      color: C.textDark,
    },
    groupChipTextSelected: {
      fontSize: 12,
      color: C.buttonText,
      fontWeight: '600',
    },
    profileCard: {
      backgroundColor: C.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
    },
    profileTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    profileAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: C.primary + '15',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    profileAvatarText: {
      fontSize: 20,
      fontWeight: '700',
      color: C.primaryDark,
    },
    profileName: {
      fontSize: 16,
      fontWeight: '700',
      color: C.textDark,
    },
    profileEmail: {
      fontSize: 13,
      color: C.textMuted,
    },
    profileEditButton: {
      borderWidth: 1,
      borderColor: C.primary,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
    },
    profileEditButtonText: {
      color: C.primary,
      fontSize: 12,
      fontWeight: '600',
    },
    profileInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    profileInfoItem: {
      alignItems: 'center',
      flex: 1,
    },
    profileInfoLabel: {
      fontSize: 12,
      color: C.textMuted,
      marginBottom: 4,
    },
    profileInfoValue: {
      fontSize: 14,
      fontWeight: '600',
      color: C.textDark,
    },
    profileStatsRow: {
      flexDirection: 'row',
      marginTop: 12,
    },
    profileStatBox: {
      flex: 1,
      backgroundColor: C.border + '20',
      padding: 12,
      borderRadius: 12,
      marginRight: 8,
    },
    profileStatLabel: {
      fontSize: 12,
      color: C.textMuted,
      marginBottom: 4,
    },
    profileStatValue: {
      fontSize: 18,
      fontWeight: '700',
      color: C.textDark,
    },
    statsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: C.primary + '15',
      borderWidth: 1,
      borderColor: C.primary,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    statsButtonText: {
      fontSize: 12,
      fontWeight: '700',
      color: C.primaryDark,
    },
    statsOverlayBackdrop: {
      flex: 1,
      backgroundColor: C.backdrop,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    statsOverlay: {
      backgroundColor: C.card,
      borderRadius: 20,
      padding: 24,
      width: '100%',
      shadowColor: C.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: C.shadowOpacity,
      shadowRadius: 16,
      elevation: 10,
    },
    statsOverlayTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: C.textDark,
      marginBottom: 4,
    },
    statsOverlaySubtitle: {
      fontSize: 13,
      color: C.textMuted,
      marginBottom: 18,
    },
    statsEmptyText: {
      fontSize: 14,
      color: C.textMuted,
      textAlign: 'center',
      paddingVertical: 12,
    },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: C.border,
    },
    statsMuscle: {
      fontSize: 14,
      fontWeight: '600',
      color: C.textDark,
      flex: 1,
    },
    statsValues: {
      flexDirection: 'row',
      gap: 6,
    },
    statsChip: {
      backgroundColor: C.chipBackground,
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    statsChipGreen: {
      backgroundColor: C.statsGreenBg,
    },
    statsChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: C.textMuted,
    },
  });
  _stylesCache.set(isDark, sheet);
  return sheet;
};

// Backwards compatibility default styles object
export const styles = getStyles(false);
